theme: jekyll-theme-midnight
google_analytics: true
github:
  private: false
  license: MIT
kramdown:
  parse_block_html: true

excerpt_separator: <!--below excerpt-->

source              : .
destination         : ./_site
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  proposals:
    output: true
    permalink: /:collection/:name
  minutes:
    output: true
    permalink: /:collection/:name
  posts:
    output: true

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1

# https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl             : "/S-RCWG" # does not include hostname
url                 : "https://sainsburywellcomecentre.github.io"
show_dir_listing    : false